import type { IncomingMessage, ServerResponse } from "http";
import type { GetServerSideProps, NextPage } from "next";
import { createRouter } from "next-connect";
import Head from "next/head";
import type { User } from "../../common/api";
import { getUsers } from "../../common/api";
import styles from "../../styles/styles.module.css";

interface PageProps {
  user: User;
}

const UserPage: NextPage<PageProps> = ({ user }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>All Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://github.com/hoangvvo/next-connect/tree/main/examples/nextjs/pages/gssp.tsx">
            getServerSideProps
          </a>{" "}
          Example
        </h1>
        <h2>
          My name is {user.name}. I am {user.age} years old
        </h2>
      </main>
    </div>
  );
};

export default UserPage;

const gsspRouter = createRouter<
  IncomingMessage & { body?: Record<string, string | number> },
  ServerResponse
>().get((req) => {
  const users = getUsers(req);
  // @ts-ignore: this is attached earlier
  const user = users.find((user) => user.id === req.params.id);
  if (!user) {
    return {
      notFound: true,
      props: {},
    };
  }
  return {
    props: {
      user,
    },
  };
});

export const getServerSideProps: GetServerSideProps<PageProps> = async ({
  req,
  res,
  params,
}) => {
  // @ts-ignore: attach params to req.params
  req.params = params;
  return gsspRouter.run(req, res) as any;
};
