import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/styles.module.css";

const ApiRoutesPage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://github.com/hoangvvo/next-connect/tree/main/examples/nextjs">
            API Routes example
          </a>
        </h1>
        <p>Open your devtool and try the following snippets.</p>
        <div>
          <h2>
            <code style={{ color: "rgb(212,0,255)" }}>POST /api/users</code>
            <span> - Create a user</span>
          </h2>
          <code>
            <pre>{`await fetch("/api/users", {
  headers: { "content-type": "application/json" },
  body: JSON.stringify({ name: "Jane Doe", age: 18 }),
}).then((res) => res.json());
`}</pre>
          </code>
          <h2>
            <code style={{ color: "rgb(212,0,255)" }}>GET /api/users</code>
            <span> - Get all users</span>
          </h2>
          <code>
            <pre>{`await fetch("/api/users").then((res) => res.json());
`}</pre>
          </code>
          <h2>
            <code style={{ color: "rgb(212,0,255)" }}>GET /api/users/:id</code>
            <span> - Get a single user</span>
          </h2>
          <code>
            <pre>
              {`await fetch("/api/users/`}
              <span style={{ color: "rgb(212,0,255)" }}>some-id</span>
              {`").then(res => res.json());
`}
            </pre>
          </code>
        </div>
      </main>
    </div>
  );
};

export default ApiRoutesPage;
